
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ulviyehacizade
 */
public class Success extends javax.swing.JFrame {
    String gender;
    /**
     * Creates new form Success
     */
    public Success() {
        initComponents();
        show_user();
    }
    public ArrayList<User> userList()
    {
       ArrayList<User> userList = new ArrayList<>();
       try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");//internetten arama motoruna "java sql server connection string"
            String url = "jdbc:sqlserver://localhost : 1433;databaseName = testdb; user = sa; password = Halic123";
            Connection con = DriverManager.getConnection(url);
            String query1 = "select * from users";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            User user;
            
            while(rs.next())
            {
                user = new User(rs.getInt("uid"),rs.getString("name"), rs.getString("address"), rs.getString("gender"), rs.getString("course"), rs.getString("subject"));
                userList.add(user);
            }
        }
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
       return userList;
    }
    public void show_user()
    {
        ArrayList<User> list = userList();
        DefaultTableModel model = (DefaultTableModel)j_TableDisplay.getModel();
        Object[] row = new Object[6];
        for(int i = 0; i < list.size(); i++)
        {
            row[0] = list.get(i).getuid();
            row[1] = list.get(i).getname();
            row[2] = list.get(i).getaddress();
            row[3] = list.get(i).getgender();
            row[4] = list.get(i).getcourse();
            row[5] = list.get(i).getsubject();
            model.addRow(row);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        Java = new javax.swing.JCheckBox();
        C = new javax.swing.JCheckBox();
        subject = new javax.swing.JComboBox<>();
        Save = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        j_TableDisplay = new javax.swing.JTable();
        update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Adress");

        jLabel3.setText("Gender");

        jLabel4.setText("Course");

        jLabel5.setText("Subject");

        buttonGroup1.add(female);
        female.setText("Female");

        buttonGroup1.add(male);
        male.setText("Male");

        Java.setText("Java");

        C.setText("C");

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Engineering", "Management", "Arts", "Electric-Electronic Engineering" }));

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Reset.setText("Reset");

        j_TableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "uid", "name", "address", "gender", "course", "subject"
            }
        ));
        j_TableDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_TableDisplayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(j_TableDisplay);

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Java)
                                .addGap(38, 38, 38)
                                .addComponent(C))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(female)
                                .addGap(47, 47, 47)
                                .addComponent(male))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(name)
                                .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(female)
                    .addComponent(male))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Java)
                    .addComponent(C))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Reset)
                    .addComponent(update)
                    .addComponent(Delete))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");//internetten arama motoruna "java sql server connection string"
            String url = "jdbc:sqlserver://localhost : 1433;databaseName = testdb; user = sa; password = Halic123";
            Connection con = DriverManager.getConnection(url);
            String query = "insert into users (name, address, gender, course, subject) values (?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, name.getText());
            pst.setString(2, address.getText());
            if(female.isSelected())
            {
                gender = "Female";
            }
            if(male.isSelected())
            {
                gender = "Male";
            }
            pst.setString(3, gender);
            String course = "";
            if(Java.isSelected())
            {
                course += Java.getText() + "";
            }
            if(C.isSelected())
            {
                course += C.getText()+ "";
            }
            pst.setString(4, course);
            String s = "";
            s = subject.getSelectedItem().toString();
            pst.setString(5, s);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Succesfully");
            con.close();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
     show_user();
    }//GEN-LAST:event_SaveActionPerformed

    private void j_TableDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_TableDisplayMouseClicked
        int i = j_TableDisplay.getSelectedRow();
        TableModel model = j_TableDisplay.getModel();
        
        name.setText(model.getValueAt(i, 1).toString());
        address.setText(model.getValueAt(i, 2).toString());
        
        String gender1 = model.getValueAt(i,3).toString();
        if(gender1.equals("Female"))
            female.setSelected(true);
        else
            male.setSelected(true);
        
        String course1 = model.getValueAt(i,4).toString();
        switch(course1){
            case "Java":
                Java.setSelected(true);
                C.setSelected(false);
                break;
            case "C":
                 Java.setSelected(false);
                C.setSelected(true);
                break;
            default:
                 Java.setSelected(true);
                C.setSelected(true);
        }
        
        String subject1 = model.getValueAt(i,5).toString();
        
        switch(subject1){
            case "Computer Engineering":
                subject.setSelectedIndex(0);
                break;
            case "Management":
                subject.setSelectedIndex(1);
                break;
            case " Arts":
               subject.setSelectedIndex(2);
               break;
            case "Electric-Electronic Engineering":
                subject.setSelectedIndex(3);
                break;
        }
    }//GEN-LAST:event_j_TableDisplayMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
             Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");//internetten arama motoruna "java sql server connection string"
            String url = "jdbc:sqlserver://localhost : 1433;databaseName = testdb; user = sa; password = Halic123";
            Connection con = DriverManager.getConnection(url);
            int row = j_TableDisplay.getSelectedRow();
            String value =( j_TableDisplay.getValueAt(row, 0).toString());
            
            String query4 = "Update users set name = ?, address = ?, gender = ?, course = ?, subject = ? where uid = " + value;
            
            PreparedStatement pst = con.prepareStatement(query4);
            pst.setString(1, name.getText());
            pst.setString(2, address.getText());
            if(female.isSelected())
            {
                gender = "Female";
            }
            if(male.isSelected())
            {
                gender = "Male";
            }
            pst.setString(3, gender);
            String course = "";
            if(Java.isSelected())
            {
                course += Java.getText() + "";
            }
            if(C.isSelected())
            {
                course += C.getText()+ "";
            }
            pst.setString(4, course);
            String subjects;
            subjects = subject.getSelectedItem().toString();
            pst.setString(5,subjects);
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)j_TableDisplay.getModel();
            model.setRowCount(0);
            show_user();
             JOptionPane.showMessageDialog(null, "Update success");
              con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        
        int opt = JOptionPane.showConfirmDialog(null, "Are you sure to delete","Delete", JOptionPane.YES_NO_OPTION);
        if(opt == 0){
            try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");//internetten arama motoruna "java sql server connection string"
            String url = "jdbc:sqlserver://localhost : 1433;databaseName = testdb; user = sa; password = Halic123";
            Connection con = DriverManager.getConnection(url);
            int row = j_TableDisplay.getSelectedRow();
            String value = (j_TableDisplay.getModel().getValueAt(row, 0)).toString();
            String query5 ="delete from users where uid = " + value;
            PreparedStatement pst = con.prepareStatement(query5);
            
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)j_TableDisplay.getModel();
            model.setRowCount(0);
            show_user();
            JOptionPane.showMessageDialog(null, "Update success");
             con.close();
        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
        
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Success.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Success().setVisible(true);
            }
        });
              
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox C;
    private javax.swing.JButton Delete;
    private javax.swing.JCheckBox Java;
    private javax.swing.JButton Reset;
    private javax.swing.JButton Save;
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable j_TableDisplay;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
